# Generated by Django 4.1.2 on 2022-11-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineplex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showing',
            name='last_row',
            field=models.TextField(null=True),
        ),
    ]
