# Generated by Django 4.1.2 on 2023-02-20 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cineplex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_audited', models.DateTimeField()),
                ('audit_log', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cineplex.movie')),
            ],
        ),
    ]
